language: node_js
node_js:
  - "8"
install:
  - npm install
before_deploy:
  - npm test
deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key:
    secure: '$HEROKU_API_KEY'
  on:
    branch: master

    