language: node_js
node_js:
- '8'
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  app: $HEROKU_APP_NAME
  api_key:
    secure: TRB7BsgSba0MenVIx4hgoHP0KYFrsSX2Oqm1ArJcOBUUxohDdQHJlriI/B90LFvx2fGNTagLsj0ATqoIlVHSVfU92xYG9emBhVqIHNT8YDTF7Gxy23HNETTCO4gwqICedLmuPE7YkjjIt1MwB0x3fViGlfD31HWa0IK8QJqT5fSDRcxagNcAl0mVv1jNLAS4a9SiKS7Yp2lKNepAR6vmb8LJmKVlwXYuNz9sBBEx+abuJ/yNgQHonNSJ0LwE8UTTkR6jnogyZtmvULKCE7+yutbqlGaoLkhwVfWyvNdlEHwblMWsedoaFE8PHn0VYo0YdeO06dGp/IC4ibxVWPeD95U28u/JYsmYXZzwvXO7KWlZn579RD4CCCt4qbZZX63kot/P9WgvGtwIdKVGnT6EdDdrZqI3tmZ3kg3Pecpve2Vn+W7xNi+62lQBjT9D++XUzm4oWHTYVVzinw1+ofCbjxiGF5di1uza355ACBYy/eebEgXT6TrV7njR5B7h4ibpo8P5Na9sZwUnRx5TxTklckKSriivrRJhuqSxC+ht83RnCKZVW0SdLLSEZbJszn3yruBCGlnD5k++mX5nP692ZW9BrDzFUx4yLyjDr3tWYC7s3nTgz5VahcKnRHL3nYHF9WS7riFSOEc+1+n8jOCsXOCIDV9V5LoLCKmcZK7UITk=
  on:
    branch: master
